pipeline {
    agent any

    tools {
    maven "Maven3"
}

environment {
      PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
      DOCKERHUB_CREDENTIALS_ID = '20245d70-153c-4562-b3d5-7907fff8f1fa'
      DOCKERHUB_REPO = 'nooav/week_6_assignment'
      DOCKER_IMAGE_TAG = 'latest'
  }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/NooaV-M/Software-Engineering-Project-1-2026-Assignments.git'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Code Coverage') {
            steps {
                bat 'mvn org.jacoco:jacoco-maven-plugin:0.8.12:report'
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }
        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }
        stage('Build Docker Image') {
                  steps {
                      script {
                          // Build using the Dockerfile located in Week6-Assignment. Use the workspace root as build context so parent POM is available.
                          docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}", "-f Week6-Assignment/Dockerfile .")
                      }
                  }
              }

          stage('Push Docker Image to Docker Hub') {
              steps {
                  script {
                      docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                          docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                      }
                  }
              }
          }
    }
}