pipeline {
    agent any

    tools {
    maven "Maven3"
}

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/NooaV-M/Software-Engineering-Project-1-2026-Assignments.git'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Code Coverage') {
            steps {
                bat 'mvn org.jacoco:jacoco-maven-plugin:0.8.12:report'
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }
        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }
        stage('Build Docker Image') {
                  steps {
                      script {
                          docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                      }
                  }
              }

              stage('Push Docker Image to Docker Hub') {
                  steps {
                      script {
                          docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                              docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                          }
                      }
                  }
              }
    }
}