pipeline {
    agent any

    tools {
    maven "Maven3"
}

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/NooaV-M/Software-Engineering-Project-1-2026-Assignments.git'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Code Coverage') {
            steps {
                bat 'mvn jacoco:report'
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }
        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }
    }
}